import 'server-only';
import type {
  Classification,
  DraftFlag,
  LlmFailureKind,
  RefusalCategory,
  ToneStyle,
  ValidationErrorCode,
} from '@/server/domain/types';

// The LLM port never throws for API or output problems: every outcome is an LlmResult (D-24).
// Lead-controlled text (message, names, company, form name, page text) is wrapped in untrusted-input
// delimiters by the adapter. Values are parsed with Zod after lower-casing enum strings; limits the
// JSON schema cannot express (faq count, word limits) are enforced by callers.

export interface LlmUsage {
  inputTokens: number;
  /** Includes thinking tokens. */
  outputTokens: number;
  cacheReadTokens?: number | undefined;
  cacheWriteTokens?: number | undefined;
}

export interface LlmSuccess<T> {
  ok: true;
  value: T;
  usage: LlmUsage;
  /** The API's `stop_reason` (`end_turn` for any accepted value). */
  stopReason: string;
  /** The model that served the request (`response.model`); costs are keyed by it (D-25). */
  model: string;
  requestId?: string | undefined;
}

export interface LlmFailure {
  ok: false;
  /**
   * `refusal`: no retry, needs-touch (or the empty brief form). `max_tokens`: counts as the one retry.
   * `invalid_output`: JSON/Zod failure. `transient`: the job returns 5xx. `fatal_config`: needs-touch
   * at once plus an admin alert (400/401/403/404/402/413, spend cap).
   */
  failure: LlmFailureKind;
  retryAfterMs?: number | undefined;
  model?: string | undefined;
  /** Present when the API answered (a refusal or truncation still reports usage). */
  usage?: LlmUsage | undefined;
  stopReason?: string | undefined;
  requestId?: string | undefined;
  /** `stop_details.category` for a refusal; `null` when the API gives none. */
  refusalCategory?: RefusalCategory | null | undefined;
  /** Machine-readable detail, e.g. `spend_cap`, `model_not_found`, `aborted`. Never an SDK message. */
  errorCode?: string | undefined;
}

export type LlmResult<T> = LlmSuccess<T> | LlmFailure;

/** Per-call options for the short calls; the signal bounds SDK retries to the function budget. */
export interface LlmCallOptions {
  signal?: AbortSignal | undefined;
}

export interface ClassifyInput {
  message: string | null;
  formName: string;
  firstName: string | null;
  company: string | null;
}

export interface ClassifyOutput {
  classification: Classification;
  /** A short machine-readable reason, never prose. */
  reason_code?: string | undefined;
}

export interface BriefTone {
  style: ToneStyle;
  note: string;
}

export interface BriefFaq {
  q: string;
  a: string;
}

/** The business brief (brief §5.3): generated by the model, then edited and saved by the owner. */
export interface BriefDraft {
  company_name: string;
  one_line: string;
  services: string[];
  who_we_serve: string;
  /** https only, and it must appear in the fetched pages; the owner confirms it (D-47). */
  booking_link: string | null;
  tone: BriefTone;
  sign_off_name: string;
  /** Generated briefs always start with `false`, whatever the model says (D-24). */
  allow_pricing: boolean;
  never_promise: string[];
  /** At most 8, enforced in code. */
  faqs: BriefFaq[];
}

/** Text extracted from one fetched page (nav, scripts and hidden DOM already stripped). */
export interface BriefPage {
  url: string;
  text: string;
}

export interface GenerateBriefInput {
  pages: readonly BriefPage[];
  sourceUrl: string;
}

export interface GenerateBriefOptions {
  /** Remaining budget; used as both the SDK timeout and an abort signal. */
  timeoutMs: number;
  /**
   * 0 on the first delivery (adaptive thinking, ANTHROPIC_BRIEF_EFFORT, 16000 tokens). 1 or more selects
   * the fallback parameters (`between_tools`/high/4096); callers also pass ≥ 1 after an aborted attempt.
   */
  attempt: number;
}

/** The lead fields a draft may use: no other CRM data (brief §5.4). */
export interface DraftLeadInput {
  firstName: string | null;
  company: string | null;
  message: string | null;
  formName: string;
}

/** Why the previous attempt was rejected; `max_tokens` makes the retry use a larger token budget. */
export type DraftRetryCode = ValidationErrorCode | 'invalid_output' | 'max_tokens';

export interface DraftInput {
  brief: BriefDraft;
  lead: DraftLeadInput;
  /** Empty on the first attempt; the retry is a fresh single-turn request carrying these codes. */
  previousErrorCodes: readonly DraftRetryCode[];
}

export interface FollowUpDraftInput extends DraftInput {
  followUpNumber: 1 | 2;
  /** The initial draft, while its content still exists; `null` once purged (PLAN §9.5). */
  original: { subject: string; body: string } | null;
}

export interface DraftOutput {
  subject: string;
  body: string;
  used_booking_link: boolean;
  flags: DraftFlag[];
}

export interface LLM {
  /** Classifies a submission with the fast model; callers turn any failure into `unclear` (D-24). */
  classify(input: ClassifyInput, options?: LlmCallOptions): Promise<LlmResult<ClassifyOutput>>;

  /** Drafts the business brief from crawled pages with the draft model (PLAN §9.7). */
  generateBrief(input: GenerateBriefInput, options: GenerateBriefOptions): Promise<LlmResult<BriefDraft>>;

  /** Drafts the owner's first reply to a lead (≤120 words; checked by the validator). */
  draft(input: DraftInput, options?: LlmCallOptions): Promise<LlmResult<DraftOutput>>;

  /** Drafts follow-up n (≤70 words), referencing the original while it exists. */
  draftFollowUp(input: FollowUpDraftInput, options?: LlmCallOptions): Promise<LlmResult<DraftOutput>>;
}
